name: Build & Draft Release Kivy APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install System Dependencies
        run: |
          sudo apt update && sudo apt install -y \
          zip unzip build-essential git openjdk-17-jdk \
          libssl-dev libffi-dev ccache autoconf automake \
          libtool pkg-config python3-dev

      - name: Install Buildozer & Dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Build APK with Buildozer
        run: |
          # Check if buildozer.spec already exists, if not, run buildozer init
          if [ ! -f buildozer.spec ]; then buildozer init; fi
          buildozer -v android debug

      - name: Verify APK Build
        run: |
          if [ ! -f bin/*.apk ]; then
            echo "APK build failed"
            exit 1
          fi

      - name: Upload APK as Artifact (for testing)
        uses: actions/upload-artifact@v3
        with:
          name: kivy-apk
          path: bin/*.apk

      - name: Create Draft Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: draft-${{ github.run_id }}
          name: "Draft release - Build #${{ github.run_number }}"
          draft: true
          files: bin/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
